[project]
name = "acme-company-mcp"
version = "0.1.0"
description = "Acme Company MCP server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.3",
    "mcp[cli]>=1.6.0",
    "requests>=2.32.0",
    "fastmcp>=2.6.1",
    "httpx>=0.28.1",
]